const tags = [
  {id: 1, tagName: 'vue'},
  {id: 2, tagName: 'vue-axios'},
  {id: 3, tagName: 'Vue-router'},
  {id: 4, tagName: 'VUEX'},
  {id: 5, tagName: 'react'},
  {id: 6, tagName: 'angular'},
  {id: 7, tagName: 'angular'},
  {id: 8, tagName: 'angular'},
  {id: 9, tagName: 'angular'},
  {id: 10, tagName: 'angular'},
  {id: 11, tagName: 'cngular'},
  {id: 12, tagName: 'nngular'},
  {id: 13, tagName: 'zngular'},
  {id: 14, tagName: 'xngular'},
  {id: 15, tagName: 'qngular'},
  {id: 16, tagName: 'angular'},
  {id: 17, tagName: 'wngular'},
  {id: 18, tagName: 'yngular'},
  {id: 19, tagName: 'tngular'},
  {id: 20, tagName: 'angular'},
  {id: 21, tagName: 'Vue'},
]

module.exports = tags